<?php

return [
    'automata_sebessegvalto' => 'automata sebességváltó',
    'automata_3_fokozatu_sebessegvalto' => 'automata (3 fokozatú) sebességváltó',
    'automata_4_fokozatu_sebessegvalto' => 'automata (4 fokozatú) sebességváltó',
    'automata_5_fokozatu_sebessegvalto' => 'automata (5 fokozatú) sebességváltó',
    'automata_6_fokozatu_sebessegvalto' => 'automata (6 fokozatú) sebességváltó',
    'automata_7_fokozatu_sebessegvalto' => 'automata (7 fokozatú) sebességváltó',
    'automata_8_fokozatu_sebessegvalto' => 'automata (8 fokozatú) sebességváltó',
    'automata_9_fokozatu_sebessegvalto' => 'automata (9 fokozatú) sebességváltó',
    'automata_10_fokozatu_sebessegvalto' => 'automata (10 fokozatú) sebességváltó',
    'felautomata_sebessegvalto' => 'félautomata sebességváltó',
    'fokozatmentes_automata_sebessegvalto' => 'fokozatmentes automata sebességváltó',
    'manualis_sebessegvalto' => 'manuális sebességváltó',
    'manualis_3_fokozatu_sebessegvalto' => 'manuális (3 fokozatú) sebességváltó',
    'manualis_4_fokozatu_sebessegvalto' => 'manuális (4 fokozatú) sebességváltó',
    'manualis_5_fokozatu_sebessegvalto' => 'manuális (5 fokozatú) sebességváltó',
    'manualis_6_fokozatu_sebessegvalto' => 'manuális (6 fokozatú) sebességváltó',
    'manualis_7_fokozatu_sebessegvalto' => 'manuális (7 fokozatú) sebességváltó',
    'szekvencialis_sebessegvalto' => 'szekvenciális sebességváltó',
    'szekvencialis_4_fokozatu_sebessegvalto' => 'szekvenciális (4 fokozatú) sebességváltó',
    'szekvencialis_5_fokozatu_sebessegvalto' => 'szekvenciális (5 fokozatú) sebességváltó',
    'szekvencialis_6_fokozatu_sebessegvalto' => 'szekvenciális (6 fokozatú) sebességváltó',
    'szekvencialis_7_fokozatu_sebessegvalto' => 'szekvenciális (7 fokozatú) sebességváltó',
    'szekvencialis_8_fokozatu_sebessegvalto' => 'szekvenciális (8 fokozatú) sebességváltó',
    'tiptronic_sebessegvalto' => 'tiptronic sebességváltó',
    'automata_4_fokozatu_tiptronic_sebessegvalto' => 'automata (4 fokozatú tiptronic) sebességváltó',
    'automata_5_fokozatu_tiptronic_sebessegvalto' => 'automata (5 fokozatú tiptronic) sebességváltó',
    'automata_6_fokozatu_tiptronic_sebessegvalto' => 'automata (6 fokozatú tiptronic) sebességváltó',
    'automata_7_fokozatu_tiptronic_sebessegvalto' => 'automata (7 fokozatú tiptronic) sebességváltó',
    'automata_8_fokozatu_tiptronic_sebessegvalto' => 'automata (8 fokozatú tiptronic) sebességváltó',
    'automata_9_fokozatu_tiptronic_sebessegvalto' => 'automata (9 fokozatú tiptronic) sebességváltó',
];