<?php

return [

    'barna' => 'barna',
    'sotetbarna' => 'sötétbarna',
    'vilagosbarna' => 'világosbarna',
    'bezs' => 'bézs',
    'biborvoros' => 'bíborvörös',
    'bordo' => 'bordó',
    'ezust' => 'ezüst',
    'feher' => 'fehér',
    'tort_feher' => 'tört fehér',
    'fekete' => 'fekete',
    'homok' => 'homok',
    'ibolya' => 'ibolya',
    'kek' => 'kék',
    'ibolyakek' => 'ibolyakék',
    'oceankek' => 'óceánkék',
    'sotetkek' => 'sötétkék',
    'vilagoskek' => 'világoskék',
    'lila' => 'lila',
    'narancs' => 'narancs',
    'okker' => 'okker',
    'pezsgo' => 'pezsgő',
    'piros' => 'piros',
    'rozsaszin' => 'rózsaszín',
    'sarga' => 'sárga',
    'aranysarga' => 'aranysárga',
    'citromsarga' => 'citromsárga',
    'naracssarga' => 'narancssárga',
    'szurke' => 'szürke',
    'sotetszurke' => 'sötétszürke',
    'vilagosszurke' => 'világosszürke',
    'terep' => 'terep',
    'turkiz' => 'türkiz',
    'vajszinu' => 'vajszínű',
    'zold' => 'zöld',
    'olajzold' => 'olajzöld',
    'sotetzold' => 'sötétzöld',
    'vilagoszold' => 'világoszöld',
];